### ISSUE TITLE
.is-exiting on firefox problem

### ISSUE THREAD

**Issue by stigk** [miguel-perez/smoothState.js#127]
On firefox page exit animation plays then the elements come back to their original position.

The issue is not there when i test it on local, when i upload it to the server if i press back button or use a link in navigation the page exit animation plays then positions back.

The issue is not there in the smoothstate.js demo website so im not sure where im going wrong even adding -moz- prefix to alternate-reverse does not seem to fix it.

any tips on the fix will be really appreciated.

Chrome has no such issues, i have added chrome prefix.

Great job with the plugin, really good.

EDIT : managed to fix it, added page cache that is some how fixing it.
had to upload to a server to test since on local it does not fire .is-exiting just gives a white flash.

**Comment by cstyves** [comment]
This is a real issue.

I'm having the exact same problem since yesterday, it look's like Firefox remove the class mid animation (I've change my animation time to 2s) and the class "is-exiting" is removed after 1 second and the animation flick to 0%.

Thanks for the caching solution I will give it a try.

**Comment by chinghanho** [comment]
duplicate #125
