### ISSUE TITLE
smoothState and CMS integration

### ISSUE THREAD

**Issue by darknailblue** [miguel-perez/smoothState.js#130]
Hi!

I've attempted to use smoothState on a site of mine, and I believe that I fully understand the concept behind it.  However being that I'm using WordPress I've hit a road block and need a bit of advice to move forward.

The site I'm developing has a lot of different JavaScript dependencies.  Because of how the site is constructed and how WordPress works out of the box, many of the pages have DIFFERENT dependencies and for speed reasons shouldn't all be loaded globally.

Because of this, it seems that when I load a page initially with smoothState everything works fine.  As I browse the site more and more of the components on the page that have JavaScript dependencies break making the site unusable at that point.

Additionally, some of the elements are created dynamically from page to page (ie parallax background, etc.) and from page to page, carry over and are not properly destroyed, or initialized.

What I want to know how to do, is how I can approach loading these dependencies on a page per page basis.  Is this possible with smoothState or do all dependencies need to be loaded right away?

Any kind of help will be much appreciated.  Thanks in advance.

**Comment by miguel-perez** [comment]
This is a rough problem. The ideal scenario is being able to initialize any additional plugins on the [callback method](https://github.com/miguel-perez/smoothState.js/blob/master/README.md#callback) so that you can bind all of the plugins after the new content has been injected. 

The problem with a CMS like wordpress, like you described, is that the site's javascript is rarely in such a neat shape where you can just execute the plugins as you need them. I've tried do solve this by rewriting the `$.fn.ready()` function to instead be a module execution controller. Here's what I did:
1. Put all the scripts within the document ready function
2. Make sure all of the needed JS is either on the initial page load, or gets returned from the server inside of the smoothState container.
3. Include [this script](https://gist.github.com/miguel-perez/476046a42d229251fec3) right after jQuery
4. On `options.callback()` run `$.readyFn.execute();`

This workaround is far from perfect, and it makes me cringe a little. There have been some discussion about this in the past:
- https://github.com/miguel-perez/smoothState.js/issues/77
- https://github.com/miguel-perez/smoothState.js/issues/109

I hope it helps.

**Comment by miguel-perez** [comment]
I've realized it would best to move [personal support](https://github.com/miguel-perez/smoothState.js#need-help) requests over to Stack Overflow. There's a special [smoothstate.js](http://stackoverflow.com/tags/smoothstate.js) label for us there. This will help us keep the Github issue tracker clean for bugs, pull requests, and enhancements. If you're not having any luck on Stack Overflow, feel free to join the [Gitter room](https://gitter.im/miguel-perez/smoothState.js) and ping me there. I'll try to help as much as I can.

That said, I'll be closing out this issue.
