### ISSUE TITLE
hover throttle

### ISSUE THREAD

**Issue by thisisjamessmith** [miguel-perez/smoothState.js#150]
It would be nice if we could somehow throttle the prefetching so that when a user hovers over a long list of links in turn they are not all fetched, as this massively slows down a site. I guess it could also potentially bring down a server with enough simultaneous traffic.

Just thinking out loud, but is it possible to cancel an ajax request after it has been sent? That way we could ensure that only a single fetch request is in progress.

Or maybe if the pageCacheSize property could also apply to prefetching?

**Comment by thisisjamessmith** [comment]
Actually I've just noticed all the work that has been done already on this issue in another branch, but was reverted for some reason...?

**Comment by miguel-perez** [comment]
@thisisjamessmith I was thinking about how best to support this without actually re-building something like hoverIntent, especially since it's so device dependent. I was thinking we could open up the events to be a configurable option.

For example, here:https://github.com/miguel-perez/smoothState.js/blob/master/src/jquery.smoothState.js#L532

instead of:

``` js
bindEventHandlers = function ($element) {
  //@todo: Handle form submissions
  $element.on('click', options.anchors, clickAnchor);
  if (options.prefetch) {
      $element.on('mouseover touchstart', options.anchors, hoverAnchor);
  }
},
```

we could do something like:

``` js
  if (options.prefetch) {
      $element.on(options.anchorPrefetchEvent, options.anchors, hoverAnchor);
  }
```

That way you can define your own events that fire at any given throttle, and you can use external plugins to define that for you.

**Comment by miguel-perez** [comment]
Added.

**Comment by thisisjamessmith** [comment]
Thanks Miguel, this looks like an interesting approach. I ended up reverse-engineering the previous commit from the alternative branch and that seems to be working well, but obviously going forward the new prefetchOn option would be best. A bit unsure as to what that custom event would actually do, however - can you make an example?

**Comment by miguel-perez** [comment]
Sure thing, here's what I'm thinking:

In order to add a smart throttle, you can use a lirbary like @tristen's [hoverintent](https://github.com/tristen/hoverintent) and trigger a custom 'intent' event. Then, you just add that to the `prefetchOn` option.

``` js
$(‘#main’).smoothState({ prefetchOn:'intent' });
```

Or, if you want to get a little crazy, you could go the opotsite way and use @cihadturhan's [jQuery.aim](https://github.com/cihadturhan/jquery-aim) and add spider sense-like prefetching to smoothState.

``` js
$(‘#main’).smoothState({ prefetchOn:'aim' });
```

**Comment by thisisjamessmith** [comment]
Thanks I see. But those plugins wouldn't stop the ajax requests from being triggered in the first place (as long as the user hovers slowly enough on each link in turn), whereas the approach in the alternative branch checked for currently running requests (the prefetchOneAtTime method).

**Comment by miguel-perez** [comment]
Ah, so you mean like, a fetch queue of some sort. I'm not super convinced that's completely needed since the browser is already smart about handling multiple network requests.

If you're worried about the effects of prefetching on your server, and throttling isn't enough, it might be best to disable prefetching. 

For larger sites, it's recommended to have multiple levels of caching so that the each request doesn't hit the app server. Without this, prefetching could potentially demolish your server.

**Comment by thisisjamessmith** [comment]
Yes, we have some sophisticated layered caching in place already, and with SmoothState the site is super fast, but without the fetch queue it was definitely causing a very noticeable problem when hovering over a list of 10 links. The browser didn't seem to prevent all those multiple async ajax requests, and when finally clicking on one of them it could take 7 seconds to load instead of 0.1

**Comment by miguel-perez** [comment]
Oh snap, that's super interesting. 

Can you open up a new issue for just this? I think it's still a good idea to keep `prefetchOn`. The case your describing warrants some investigations and serious thought. Some live links would be helpful, too.

**Comment by thisisjamessmith** [comment]
Site is still in private development behind an authenticated staging server, but I might be able to put together an anonymised test case.
