### ISSUE TITLE
Question: How smoothState is different than jquery-pjax ?

### ISSUE THREAD

**Issue by jimzarkadas** [miguel-perez/smoothState.js#176]
Hi,

I have the following question: "How is smoothState different than jquery-pjax?"

I recently used jquery-pjax for a website I am developing and I faced lots of problems with the pjax:complete and document ready events. Lots of plugins didn't work right with pjax and I am thinking of giving a try to smoothState.js.

Thanks,
Jim

**Comment by miguel-perez** [comment]
> How is smoothState different than jquery-pjax?

There are some design philosophy differences between the two projects, for example:
1. smoothState gives you enough time to add page transitions animations using [special hooks](https://github.com/miguel-perez/smoothState.js#getting-started).
2. pjax expects you to send different content if you add X-PJAX headers. SmoothState doesn't care about this and requires [requires no extra back-end logic](https://github.com/miguel-perez/smoothState.js#design-philosophy-and-requirements).

> I faced lots of problems with the pjax:complete and document ready events. Lots of plugins didn't work right with pjax and I am thinking of giving a try to smoothState.js.

smoothState provides the [onAfter](https://github.com/miguel-perez/smoothState.js#onafter) callback function that would allow you to re-run your plugins. This can be tricky if you're unfamiliar with how Ajax works.

When you run a plugin on `$(document).ready()`, it's going to register _only_ on elements that are currently on the page. Since we're injecting new elements every load, we need to run the plugins again, scoping it to _just_ the new stuff. 

A good way to do this is to wrap your plugin initializations in a function that we call on both `$.fn.ready()` and `onAfter`.You'll want to specify the [context](http://api.jquery.com/jQuery/#jQuery-selector-context) each time you init the plugins so that you don't double-bind the plugins. We call this a "module execution controller".

I hope that helps.

Anyway, the Github issue tracker isn't the right place for [personal support](https://github.com/miguel-perez/smoothState.js#need-help). If you need more help, post on [stack overflow](http://stackoverflow.com/tags/smoothState.js) or join the [Gitter room](https://gitter.im/miguel-perez/smoothState.js?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge). Closing this out.

**Comment by jimzarkadas** [comment]
Great! Thanks for your feedback! :+1: I will give it a try for sure.

P.S. I didin't notice for some reason the help section sorry for that.

**Comment by miguel-perez** [comment]
:smile: :+1: Good luck! Be sure to share what you make.
