### ISSUE TITLE
Form posting to same page not being submitted

### ISSUE THREAD

**Issue by iXce** [miguel-perez/smoothState.js#189]
Hi,

I'm happily using smoothState, thanks for the great software !
I have an issue with forms which action is pointing to the current page. As far as I can tell from the Network tab from the debugger no request is actually done when submitting the form, and the page is simply reloaded from the cache.
Is this a duplicate/related to #186 ?

For now I have disabled smoothState for all forms as a workaround, but I'm hopeful there's a way to disable caching for POST'ed forms :)

**Comment by shaneparsons** [comment]
**+1** - exact same problem here

**Comment by DigitalMachinist** [comment]
I might have resolved this in a PR I've already submitted, but I'm not sure. It's difficult for me to prove that my form will never have its result cached, but it appears that it isn't caching in my tests so far. I'll hand off my changes to @miguel-perez  and hope this takes care of your issues once the PR is merged in.

My edit adds in an `options.allowFormCaching` that controls whether or not forms should ever preserve responses they get from the server in the cache. By default, I've set `allowFormCaching = false` so that your issue should be resolved by default, but end programmers can still allow their forms to be cached if they choose to accept any weirdness that might bring them.

**Comment by igoratsok** [comment]
This is an awesome plugin. Really really good job. My system looks like a SPA now.

Anyways, I'm also having the same problem. The POST is not getting updated.

**Comment by miguel-perez** [comment]
@iXce, @slumki, @shaneparsons Can you guys see if this has been fixed with @DigitalMachinist's changes? Thanks.

**Comment by igoratsok** [comment]
Thank you @DigitalMachinist and @miguel-perez.

Well, it did not. In fact, now the post doesn't even show up. It shows an error:

```
Uncaught TypeError: Cannot read property 'length' of null (jquery.smoothState.min.js:392).
```

But I think I know why (not really certain, just thinking, since I don't know much of js). The modification that @DigitalMachinist did was clearing the cache after a response is loaded using this:

```
if (!cacheResponse) {
    clear( settings.url );
}
```

I think my problem is: there are two responses in my request. So, when the first request gets into the "loaded" function, it clears the cache. Then, when the second response is loaded, the cache is already cleared. Then it gets into a null pointer exception, because it _needs_ the cache.

The solution would be clearing the cache only after all the responses are loaded. But I don't know how to do this. Do you guys have any clues?

Thank you.

**Comment by DigitalMachinist** [comment]
I'll take a look at this for you tonight to see if I can replicate it and possibly fix this for you. 

Do you mean that you are making 2 requests one after the other? Because I can't imagine how you'd be getting 2 responses to 1 request. It's possible that there's some async code operating on the queue in response to each of your requests that I'm not taking into account. I'm still fairly new to this codebase, so I could be missing something.

**Comment by DigitalMachinist** [comment]
@slumki Thanks for posting the error. I might have a fix for this upcoming. I was able to move the cache clear to a place where it will only occur after the page contents have been updated.

I'll see if I can test this out tonight and if it doesn't obviously break on my side, perhaps you can try it again with my latest changes once they're available.

**Comment by igoratsok** [comment]
@DigitalMachinist, it worked with me by just calling this:

```
if (callbBackEnded && !cacheResponse) {
    clear(settings.url);
}
```

In other words, only when the callback ended (and not everytime load() is called). And it works greatly!

Thank you.

**Comment by igoratsok** [comment]
Oh, there is still some problems.
In fact, it does not have an error, but it does not submit my form anymore correctly.
I'm trying to find a fix.

**Comment by igoratsok** [comment]
@DigitalMachinist I'm so sorry.
I was with allowFormCaching: true and didn't notice! Had a version mistake here with my files.

Using your fix (enterely, as you submitted) fixes my problem 100%! :) Thank you so, so much!

**Comment by DigitalMachinist** [comment]
Wonderful! Happy to help. Let us know if there's any trouble going forward. I want to make sure a follow through on all my fixes!
