### ISSUE TITLE
Running a different piece of jQuery on page load (help wanted)

### ISSUE THREAD

**Issue by georgewatson** [miguel-perez/smoothState.js#205]
I've seen this issue mentioned a few times, but I can't seem to make any of the solutions work. In particular, I have an object, `#portfolio`, on one page that uses Masonry.js for a nice grid layout. It works on page refresh but not when the page is navigated to properly. If I play around with the code, I can get just Masonry working or just smoothState working, but not both.

Post-butchering, here's my code. In this state, Masonry works but smoothState doesn't. Removing the entire `onEnd: {}` block reverses the situation.

```
$(function (){
  'use strict';
  var $page = $('#main'),
      options = {
        debug: true,
        prefetch: true,
        cacheLength: 2,
        onStart: {
          duration: 250, // Duration of our animation
          render: function ($container) {
            // Add your CSS animation reversing class
            $container.addClass('is-exiting');
            // Restart your animation
            smoothState.restartCSSAnimations();
          }
        },
        onReady: {
          duration: 0,
          render: function ($container, $newContent) {
            // Remove your CSS animation reversing class
            $container.removeClass('is-exiting');
            // Inject the new content
            $container.html($newContent);
          }
        }
      },
      onEnd: {
        $('#portfolio').masonry();
      }
      smoothState = $page.smoothState(options).data('smoothState');
});
```

Again, I'm aware this has been asked before, but the other solutions seem to have not worked for some reason.

**Comment by DigitalMachinist** [comment]
@dendodge So just to confirm, you've tried running your masonry reinitialization in onAfter as well? My understanding is that the onAfter hook is the officially supported hook for restarting jQuery plugins, not onEnd.

I have little experience with using smoothState in combination with other jQuery plugins that need this kind of attention but I'd like to learn my way around doing this.

I've noticed some issues in the tracker related to inconsistent documentation that hasn't been brought up to date with the current build, so that might be the issue here. Are you having trouble because of #191, by chance?

**Comment by georgewatson** [comment]
@DigitalMachinist I've tried that, and I've tried normal callbacks to call Masonry after smoothState, but it still breaks the animations.

**Comment by miguel-perez** [comment]
@dendodge this is a better conversation for StackOverflow. We need to keep the issue tracker clear for bugs.
