### ISSUE TITLE
Problem with hash-anchors + back-button

### ISSUE THREAD

**Issue by InEchtderKnecht** [miguel-perez/smoothState.js#57]
Hey, first off -  i love your plugin! But i found an issue when also using on-site hash links, which is crucial for my project right now.

For example, if you are on the demo page http://weblinc.github.io/jquery.smoothState.js/index.html , click a link and press the back button, everything is fine!

However, if the origin url also has a hash attached like this: http://weblinc.github.io/jquery.smoothState.js/index.html#main , you click a link and then the backbutton - nothing happens!

**Comment by FellowshipAgency** [comment]
This still does not work for me.

Firstly, I get the following error: 

```
Uncaught SyntaxError: Unexpected token =
line 114
```

So I removed "= null" and then I get the following error when pressing "back" or "forward" to go to a page with a hash:

```
Uncaught TypeError: Cannot read property 'href' of undefined
line 299
```

Can you help please?

Edit: Thought "back" was working, it isn't.

**Comment by idflood** [comment]
I also tested the commit in #117 from @Kalabasa and it seems to work fine for me.

As pointed by @Rubious the `= null` should be removed since default parameters are only available in ECMAScript 2015/es6 .

I haven't hit the `Uncaught TypeError`, but it seems strange. I believe it happens on this line:

```
if(page.href !== url && !utility.isHash(url, page.href)) {
```

But the page and href property should all be defined since they were already used in the unpatched version of the same line. @Rubious are you sure you didn't made a small typo when applying the commit?

**Comment by idflood** [comment]
I've found an issue with the commit in #117. Let's imagine that we are on `/smoothstate/` and click on a link which points to `/smoothstate/is#awesome`:
- `hasPathname` will be `true` since the second link effectively contains /smoothstate/
- `hasHash` will also be `true` since the new url has a hash

To fix this I'm using this on a site:

```
 isHash: function (url, prev) {
   prev = prev || window.location.pathname;
   var hasPathname = (url.indexOf(prev) >= 0) ? true : false,
       pathEnd = url.slice(url.indexOf(prev) + prev.length),
       hasHash = (url.indexOf("#") > 0) ? true : false;

    if (pathEnd !== '' && pathEnd.indexOf('#') !== 0) {
      // If we go from / to /something#new hasPathname is true.
      return false;
    }

    return (hasPathname && hasHash) ? true : false;
  }
```

The idea it that `pathEnd` will take the remaining of hasPathname, in this case `is#awesome`.

Then if pathEnd doesn't start with a `#` then it is a new url.

**Comment by somatonic** [comment]
This problem still exists. It seems there's no correct history built for when clicking a link with "samepage + #hash" on a page. So when going to another page then the back button doesn't work to "previouspage + #hash"

**Comment by FellowshipAgency** [comment]
We're still experiencing this problem.

Edit: Spoke too soon, this still does not work
